### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by chenfan9** [chenfan9/MI-449-SS17-741-html-terminal-and-git-_u9ftI#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://chenfan9.github.io/MI-449-SS17-741-html-terminal-and-git-_u9ftI/) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

**Comment by stuartpearman** [comment]
Hey Fan, looks good! :shipit: 

In the future, just wait to close these issues until you hear back from one of us
